-- Run this once in the Supabase SQL editor for the life_os project.
-- Creates the gbf_weapons table so the GBF Grid module's weapon list is
-- editable in-app (add/edit/delete) instead of hardcoded in src/modules/gbf_grid/data.ts.
--
-- Also (re-)creates gbf_grid_checked, which useGbfGrid.ts already queries for the
-- "obtained" checkbox state but which turned out not to exist in the live project --
-- that feature has likely never actually persisted anything. Both tables use the
-- same no-RLS pattern as the rest of the app (anon key only, no auth flow).

create table if not exists gbf_grid_checked (
  weapon_name text primary key
);

alter table gbf_grid_checked disable row level security;

create table if not exists gbf_weapons (
  id bigint generated always as identity primary key,
  element text not null,
  category text not null,
  name text not null,
  rank text not null default '',
  copies text not null default '',
  source text not null default '',
  created_at timestamptz not null default now()
);

alter table gbf_weapons disable row level security;

-- Seed data pulled from the gbf.wiki "Advanced Grids" pages (171 weapons, current as of the
-- Aug 2026 page snapshot). "source" (Omega Rebirth / Odious / Regalia / Ennead / Ancestral / Malice)
-- is carried over from the previous hand-curated data.ts where the name matched exactly; blank
-- for everything new -- fill those in via the app's edit UI as you go.

insert into gbf_weapons (element, category, name, rank, copies, source) values
  ('Fire', 'Core', 'Colossus Cane Ira', '151', '3–4', 'Omega Rebirth'),
  ('Fire', 'Core', 'Colossus Bomber Ira', '151', '2', 'Omega Rebirth'),
  ('Fire', 'Core', 'Nilakantha', '120', '1–2', 'Regalia'),
  ('Fire', 'Core', 'Exo Maitrah Karuna', '', '1 / 0–1', ''),
  ('Fire', 'Core', 'Scythe of Renunciation', '120', '', ''),
  ('Fire', 'Core', 'Doombringer Sword', '300', '', ''),
  ('Fire', 'Universal', 'Celestial Weapons', '', '', ''),
  ('Fire', 'Universal', 'Ultima Weapons', '', '', ''),
  ('Fire', 'Universal', 'World Weapons', '', '', ''),
  ('Fire', 'Additional', 'Sol Remnant', '', '', ''),
  ('Fire', 'Additional', 'Demonspear of Prosperity Verboten', '151', '2–3', 'Odious'),
  ('Fire', 'Additional', 'Blazefist of Prosperity Verboten', '151', '1–2', 'Odious'),
  ('Fire', 'Additional', 'Sword of Pallas Militis', '', '1', ''),
  ('Fire', 'Additional', 'Mortality Bow', '200', 'Mk II 1 / 0–1 / Unforged 1', ''),
  ('Fire', 'Additional', 'Refrain of Blazing Vigor', '200', '', ''),
  ('Fire', 'Niche', 'Deathcannon of Prosperity Verboten', '151', '1–2', 'Odious'),
  ('Fire', 'Niche', 'Extinction Blade', '200', 'Mk II 1–2 / Unforged 1–2', ''),
  ('Fire', 'Niche', 'Benbenet', '120', '1–2', 'Ennead'),
  ('Fire', 'Niche', 'Al-Abad', '120', '1 / 0–1', 'Ennead'),
  ('Fire', 'Niche', 'Colossus Buster Ira', '151', '1–2', 'Omega Rebirth'),
  ('Fire', 'Niche', 'Exo Krodha', '', '1 / 0–1', ''),
  ('Fire', 'Niche', 'Heat of The Sun', '', '', ''),
  ('Fire', 'Niche', 'Kiss of The Devil', '', '', ''),
  ('Fire', 'Niche', 'Wrathfire Militis', '', '1', ''),
  ('Fire', 'Niche', 'Garnet Broadaxe', '', '', ''),
  ('Fire', 'Niche', 'Draconic Harp', '151', '', ''),
  ('Fire', 'Niche', 'Bahamut Weapons', '130', '', ''),
  ('Fire', 'Premium', 'Crimson Scale', '', '2', ''),
  ('Wind', 'Core', 'Tiamat Bolt Aura', '151', '3–4', 'Omega Rebirth'),
  ('Wind', 'Core', 'Tiamat Edge Aura', '151', '2', 'Omega Rebirth'),
  ('Wind', 'Core', 'Exo Pelion', '', '1 / 0–1', ''),
  ('Wind', 'Core', 'Spear of Renunciation', '120', '', ''),
  ('Wind', 'Core', 'Doombringer Gauntlet', '300', '', ''),
  ('Wind', 'Universal', 'Celestial Weapons', '', '', ''),
  ('Wind', 'Universal', 'Ultima Weapons', '', '', ''),
  ('Wind', 'Universal', 'World Weapons', '', '', ''),
  ('Wind', 'Additional', 'Last Storm Harp', '120', '2–3', 'Regalia'),
  ('Wind', 'Additional', 'Gougelance of Liberation Verboten', '151', '2–3', 'Odious'),
  ('Wind', 'Additional', 'Sealhammer of Liberation Verboten', '151', '1–2', 'Odious'),
  ('Wind', 'Additional', 'Plume of Suparna Militis', '', '1', ''),
  ('Wind', 'Additional', 'Daur da Blao', '', '1', ''),
  ('Wind', 'Additional', 'Sette di Spade', '200', 'Mk II 2–3 / 0–1 / Unforged 1–2', ''),
  ('Wind', 'Additional', 'Prayer of Grand Gales', '200', '', ''),
  ('Wind', 'Niche', 'Demondagger of Liberation Verboten', '151', '1–2', 'Odious'),
  ('Wind', 'Niche', 'Spada di Vento', '200', 'Mk II 1 / 0–1 / Unforged 1', ''),
  ('Wind', 'Niche', 'Arkab Prior Militis', '', '1', ''),
  ('Wind', 'Niche', 'Tiamat Arc Aura', '151', '2', 'Omega Rebirth'),
  ('Wind', 'Niche', 'Indra''s Edge Militis', '', '1–2', ''),
  ('Wind', 'Niche', 'Mandjet', '120', '1', 'Ennead'),
  ('Wind', 'Niche', 'Ancient Nalakuvara', '40', '1', ''),
  ('Wind', 'Niche', 'Ewiyar''s Beak', '151', '1–2', 'Ancestral'),
  ('Wind', 'Niche', 'Theater of Temperance', '151', '', ''),
  ('Wind', 'Niche', 'Melody of Judgement', '151', '', ''),
  ('Wind', 'Niche', 'Peridot Crossbow', '', '', ''),
  ('Wind', 'Niche', 'Exo Australis', '', '1 / 0–1', ''),
  ('Wind', 'Niche', 'Abu Simbel', '120', '1', 'Ennead'),
  ('Wind', 'Niche', 'Bahamut Weapons', '130', '', ''),
  ('Wind', 'Niche', 'Draconic Rod', '151', '', ''),
  ('Wind', 'Premium', 'Piercing Galewing', '', '2', ''),
  ('Wind', 'Premium', 'Claíomh Solais Díon', '', '1', ''),
  ('Wind', 'Premium', 'Evanescence', '', 'MH Mainhand Only. / This weapon should not be used as a grid piece.', ''),
  ('Water', 'Core', 'Leviathan Gaze Mare', '151', '3–4', 'Omega Rebirth'),
  ('Water', 'Core', 'Leviathan Cranium Mare', '151', '1–2', 'Omega Rebirth'),
  ('Water', 'Core', 'Exo Antaeus', '', '1 / 0–1', ''),
  ('Water', 'Core', 'Staff of Renunciation', '120', '', ''),
  ('Water', 'Core', 'Doombringer Edge', '300', '', ''),
  ('Water', 'Universal', 'Celestial Weapons', '', '', ''),
  ('Water', 'Universal', 'Ultima Weapons', '', '', ''),
  ('Water', 'Universal', 'World Weapons', '', '', ''),
  ('Water', 'Additional', 'Uraeus', '120', '1', 'Ennead'),
  ('Water', 'Additional', 'Schrodinger', '200', 'Mk II 2 / 1 / Unforged 2', ''),
  ('Water', 'Additional', 'Lagrange', '200', 'Mk II 1–2 / 0–1 / Unforged 1–2', ''),
  ('Water', 'Additional', 'Demonsword of Mortality Verboten', '151', '2–3', 'Odious'),
  ('Water', 'Additional', 'Cyclestaff of Mortality Verboten', '151', '2', 'Odious'),
  ('Water', 'Additional', 'Tyros Zither', '120', '1–2', 'Regalia'),
  ('Water', 'Additional', 'Judgment of Torrential Tides', '200', '', ''),
  ('Water', 'Niche', 'Wamdus''s Cnidocyte', '151', '2', 'Ancestral'),
  ('Water', 'Niche', 'Winter''s Frostnettle', '', '', ''),
  ('Water', 'Niche', 'Ancient Auberon', '40', '1–2', ''),
  ('Water', 'Niche', 'Leviathan Spear Omega', '101', '1', ''),
  ('Water', 'Niche', 'Leviathan Blade Mare', '151', '2', 'Omega Rebirth'),
  ('Water', 'Niche', 'Terrorbow of Mortality Verboten', '151', '0–1', 'Odious'),
  ('Water', 'Niche', 'Reflection of The Moon', '151', '', ''),
  ('Water', 'Niche', 'Wilhelm Militis', '', '1–2', ''),
  ('Water', 'Niche', 'Exo Ephialtes', '', '1 / 0–1', ''),
  ('Water', 'Niche', 'Aquamarine Hatchet', '', '', ''),
  ('Water', 'Niche', 'Glacial Militis', '', '1', ''),
  ('Water', 'Niche', 'Spirit of Mana', '120', '1', 'Regalia'),
  ('Water', 'Niche', 'Draconic Buster', '151', '', ''),
  ('Water', 'Niche', 'Bahamut Weapons', '130', '', ''),
  ('Water', 'Premium', 'Gospel of Water and Sky', '', '2', ''),
  ('Earth', 'Core', 'Yggdrasil Crystal Blade Arbos', '151', '3–4', 'Omega Rebirth'),
  ('Earth', 'Core', 'Ancient Perseus', '40', '1', ''),
  ('Earth', 'Core', 'Fang of the Dragonslayer', '200', 'Mk II 3–4 / 1 / Unforged 1 / 0–1', ''),
  ('Earth', 'Core', 'Harp of Renunciation', '120', '', ''),
  ('Earth', 'Core', 'Doombringer Trident', '300', '', ''),
  ('Earth', 'Universal', 'Celestial Weapons', '', '', ''),
  ('Earth', 'Universal', 'Ultima Weapons', '', '', ''),
  ('Earth', 'Universal', 'World Weapons', '', '', ''),
  ('Earth', 'Additional', 'Lusterbow of Desire Verboten', '151', '2–3', 'Odious'),
  ('Earth', 'Additional', 'Heartstrings of Desire Verboten', '151', '2', 'Odious'),
  ('Earth', 'Additional', 'Demonedge of Desire Verboten', '151', '1–2', 'Odious'),
  ('Earth', 'Additional', 'Claw of the Dragonslayer', '200', 'Mk II 1 / 1 / Unforged 1 / 0–1', ''),
  ('Earth', 'Additional', 'Ished', '120', '1', 'Ennead'),
  ('Earth', 'Additional', 'Solomon''s Axe Militis', '', '1', ''),
  ('Earth', 'Additional', 'Yggdrasil Bark Bracer Arbos', '151', '1–2', 'Omega Rebirth'),
  ('Earth', 'Additional', 'Yggdrasil Dewdrop Harp Arbos', '151', '1–2', 'Omega Rebirth'),
  ('Earth', 'Additional', 'Bounty of Gracious Earth', '200', '', ''),
  ('Earth', 'Niche', 'Exo Ashavan', '', '1 / 0–1', ''),
  ('Earth', 'Niche', 'Tribunal Lyre Militis', '', '1', ''),
  ('Earth', 'Niche', 'Nibelung Horn', '120', '1 / Niche: 2–3', 'Regalia'),
  ('Earth', 'Niche', 'Godsworn Edge', '120', '1', 'Regalia'),
  ('Earth', 'Niche', 'Binds of The Hanged Man', '151', '', ''),
  ('Earth', 'Niche', 'Galleon''s Jaw', '151', '1', 'Ancestral'),
  ('Earth', 'Niche', 'Exo Kshathra', '', '1 / 0–1', ''),
  ('Earth', 'Niche', 'Zircon Edge', '', '', ''),
  ('Earth', 'Niche', 'Tatjenen', '120', '1', 'Ennead'),
  ('Earth', 'Niche', 'Draconic Bow', '151', '', ''),
  ('Earth', 'Niche', 'Bahamut Weapons', '130', '', ''),
  ('Earth', 'Premium', 'Pillardriver', '', '2', ''),
  ('Earth', 'Premium', 'Landslide Scepter', '', '1', ''),
  ('Light', 'Core', 'Luminiera Bolt Credo', '151', '3–4', 'Omega Rebirth'),
  ('Light', 'Core', 'Exo Heliocentrum', '', '1 / 0–1', ''),
  ('Light', 'Core', 'Sword of Renunciation', '120', '', ''),
  ('Light', 'Core', 'Doombringer Bow', '300', '', ''),
  ('Light', 'Universal', 'Celestial Weapons', '', '', ''),
  ('Light', 'Universal', 'Ultima Weapons', '', '', ''),
  ('Light', 'Universal', 'World Weapons', '', '', ''),
  ('Light', 'Additional', 'Concordia', '200', 'Mk II 1–2 / 0–1 / Unforged 1', ''),
  ('Light', 'Additional', 'Luminiera Saber Credo', '151', '1–2', 'Omega Rebirth'),
  ('Light', 'Additional', 'Exo Aristarchus', '', '1 / 0–1', ''),
  ('Light', 'Additional', 'Luminiera Lance Credo', '151', '1–2', 'Omega Rebirth'),
  ('Light', 'Additional', 'Phantom Fangs', '', '1–2', ''),
  ('Light', 'Additional', 'Radiance of Insightful Rebirth', '200', '', ''),
  ('Light', 'Niche', 'Luminiera Sword Omega', '101', '2–3', ''),
  ('Light', 'Niche', 'Pillar of Flame', '120', '2–3', 'Regalia'),
  ('Light', 'Niche', 'Harakhte', '120', '1–2 / 1', 'Ennead'),
  ('Light', 'Niche', 'Heliogabalus Militis', '', '1', ''),
  ('Light', 'Niche', 'Harsiesis', '120', '1', 'Ennead'),
  ('Light', 'Niche', 'Shooting of The Star', '151', '', ''),
  ('Light', 'Niche', 'Vital Arc', '', '', ''),
  ('Light', 'Niche', 'Draconic Blade', '151', '', ''),
  ('Light', 'Niche', 'Bahamut Weapons', '130', '', ''),
  ('Light', 'Premium', 'Harmonia', '', '2', ''),
  ('Light', 'Premium', 'White Sword of Splendor', '', '2', ''),
  ('Dark', 'Core', 'Celeste Grace Ater', '151', '3–4', 'Omega Rebirth'),
  ('Dark', 'Core', 'Celeste Saber Ater', '151', '2', 'Omega Rebirth'),
  ('Dark', 'Core', 'Exo Hamartia', '', '1 / 0–1', ''),
  ('Dark', 'Core', 'Katana of Renunciation', '120', '', ''),
  ('Dark', 'Core', 'Doombringer Lyre', '300', '', ''),
  ('Dark', 'Universal', 'Celestial Weapons', '', '', ''),
  ('Dark', 'Universal', 'Ultima Weapons', '', '', ''),
  ('Dark', 'Universal', 'World Weapons', '', '', ''),
  ('Dark', 'Additional', 'Zechariah', '120', '1', 'Regalia'),
  ('Dark', 'Additional', 'Forbidden Agastia', '200', 'Mk II 2–4 / Unforged 0–1', ''),
  ('Dark', 'Additional', 'Forsaken Agastia', '200', 'Mk II 1–2 / 0–1 / Unforged 1', ''),
  ('Dark', 'Additional', 'Celeste Dagger Ater', '151', '1–2', 'Omega Rebirth'),
  ('Dark', 'Additional', 'Abyss Spine', '120', '2', 'Regalia'),
  ('Dark', 'Additional', 'Festering of Mournful Obsequies', '200', '', ''),
  ('Dark', 'Niche', 'Pain of Death', '151', '', ''),
  ('Dark', 'Niche', 'Ancient Cortana', '40', '1', ''),
  ('Dark', 'Niche', 'Fediel''s Spine', '120', '1–2', 'Ancestral'),
  ('Dark', 'Niche', 'Ramsund Militis', '', '1–2', ''),
  ('Dark', 'Niche', 'Exo Evilenes', '', '1 / 0–1', ''),
  ('Dark', 'Niche', 'Agonize', '120', '0–2', 'Malice'),
  ('Dark', 'Niche', 'Stygian Claw', '', '', ''),
  ('Dark', 'Niche', 'Abydos', '120', '1', 'Ennead'),
  ('Dark', 'Niche', 'Vynateya Militis', '', '0–1', ''),
  ('Dark', 'Niche', 'Draconic Fire', '151', '', ''),
  ('Dark', 'Niche', 'Bahamut Weapons', '130', '', ''),
  ('Dark', 'Premium', 'Pain and Suffering', '', '2', '');
