export type Category = "Core" | "Additional" | "Niche";
export type Element = "Fire" | "Wind" | "Water" | "Earth" | "Light" | "Dark";

export interface Weapon {
  element: Element;
  category: Category;
  name: string;
  rank: string;
  copies: string;
  source: string;
}

export const ELEMENT_META: Record<Element, { boss: string; color: string; bg: string }> = {
  Fire:  { boss: "Colossus",  color: "#c0392b", bg: "#fff0ee" },
  Wind:  { boss: "Tiamat",   color: "#27ae60", bg: "#f0fdf4" },
  Water: { boss: "Leviathan",color: "#2980b9", bg: "#eff6ff" },
  Earth: { boss: "Yggdrasil",color: "#8b5e3c", bg: "#fdf6ee" },
  Light: { boss: "Luminiera",color: "#b8860b", bg: "#fffbe6" },
  Dark:  { boss: "Celeste",  color: "#6b21a8", bg: "#faf5ff" },
};

export const ELEMENTS: Element[] = ["Fire", "Wind", "Water", "Earth", "Light", "Dark"];
export const CATEGORIES: Category[] = ["Core", "Additional", "Niche"];

export const WEAPONS: Weapon[] = [
  // ── Fire (Colossus) ─────────────────────────────────────────────
  { element: "Fire", category: "Core",       name: "Colossus Cane Ira",                     rank: "151", copies: "3–4",        source: "Omega Rebirth" },
  { element: "Fire", category: "Core",       name: "Colossus Bomber Ira",                   rank: "151", copies: "2",          source: "Omega Rebirth" },
  { element: "Fire", category: "Core",       name: "Nilakantha",                            rank: "120", copies: "1–2",        source: "Regalia" },
  { element: "Fire", category: "Core",       name: "Exo Maitrah Karuna",                    rank: "—",   copies: "0–1",        source: "" },
  { element: "Fire", category: "Core",       name: "Scythe of Renunciation",                rank: "120", copies: "1",          source: "" },
  { element: "Fire", category: "Core",       name: "Doombringer Sword",                     rank: "300", copies: "1",          source: "" },
  { element: "Fire", category: "Additional", name: "Sol Remnant",                           rank: "—",   copies: "1",          source: "" },
  { element: "Fire", category: "Additional", name: "Demonspear of Prosperity Verboten",     rank: "151", copies: "2–3",        source: "Odious" },
  { element: "Fire", category: "Additional", name: "Blazefist of Prosperity Verboten",      rank: "151", copies: "1–2",        source: "Odious" },
  { element: "Fire", category: "Additional", name: "Sword of Pallas Militis",               rank: "—",   copies: "1",          source: "" },
  { element: "Fire", category: "Additional", name: "Mortality Bow",                         rank: "200", copies: "1",          source: "" },
  { element: "Fire", category: "Additional", name: "Refrain of Blazing Vigor",              rank: "200", copies: "1",          source: "" },
  { element: "Fire", category: "Niche",      name: "Deathcannon of Prosperity Verboten",    rank: "151", copies: "1–2",        source: "Odious" },
  { element: "Fire", category: "Niche",      name: "Extinction Blade",                      rank: "200", copies: "1–2",        source: "" },
  { element: "Fire", category: "Niche",      name: "Benbenet",                              rank: "120", copies: "1–2",        source: "Ennead" },
  { element: "Fire", category: "Niche",      name: "Al-Abad",                               rank: "120", copies: "0–1",        source: "Ennead" },
  { element: "Fire", category: "Niche",      name: "Colossus Buster Ira",                   rank: "151", copies: "1–2",        source: "Omega Rebirth" },
  { element: "Fire", category: "Niche",      name: "Exo Krodha",                            rank: "—",   copies: "0–1",        source: "" },
  { element: "Fire", category: "Niche",      name: "Heat of The Sun",                       rank: "—",   copies: "—",          source: "" },
  { element: "Fire", category: "Niche",      name: "Kiss of The Devil",                     rank: "—",   copies: "—",          source: "" },
  { element: "Fire", category: "Niche",      name: "Wrathfire Militis",                     rank: "—",   copies: "1",          source: "" },
  { element: "Fire", category: "Niche",      name: "Garnet Broadaxe",                       rank: "—",   copies: "—",          source: "" },
  { element: "Fire", category: "Niche",      name: "Draconic Harp",                         rank: "151", copies: "1",          source: "" },
  { element: "Fire", category: "Niche",      name: "Bahamut Weapons",                       rank: "130", copies: "1",          source: "" },

  // ── Wind (Tiamat) ────────────────────────────────────────────────
  { element: "Wind", category: "Core",       name: "Tiamat Bolt Aura",                      rank: "151", copies: "3–4",        source: "Omega Rebirth" },
  { element: "Wind", category: "Core",       name: "Tiamat Edge Aura",                      rank: "151", copies: "2",          source: "Omega Rebirth" },
  { element: "Wind", category: "Core",       name: "Exo Pelion",                            rank: "—",   copies: "0–1",        source: "" },
  { element: "Wind", category: "Core",       name: "Spear of Renunciation",                 rank: "120", copies: "1",          source: "" },
  { element: "Wind", category: "Core",       name: "Doombringer Gauntlet",                  rank: "300", copies: "1",          source: "" },
  { element: "Wind", category: "Additional", name: "Last Storm Harp",                       rank: "120", copies: "2–3",        source: "Regalia" },
  { element: "Wind", category: "Additional", name: "Gougelance of Liberation Verboten",     rank: "151", copies: "2–3",        source: "Odious" },
  { element: "Wind", category: "Additional", name: "Sealhammer of Liberation Verboten",     rank: "151", copies: "1–2",        source: "Odious" },
  { element: "Wind", category: "Additional", name: "Plume of Suparna Militis",              rank: "—",   copies: "1",          source: "" },
  { element: "Wind", category: "Additional", name: "Daur da Blao",                          rank: "—",   copies: "1",          source: "" },
  { element: "Wind", category: "Additional", name: "Sette di Spade",                        rank: "200", copies: "2–3 (Mk II)",source: "" },
  { element: "Wind", category: "Additional", name: "Prayer of Grand Gales",                 rank: "200", copies: "—",          source: "" },
  { element: "Wind", category: "Niche",      name: "Demondagger of Liberation Verboten",    rank: "151", copies: "1–2",        source: "Odious" },
  { element: "Wind", category: "Niche",      name: "Spada di Vento",                        rank: "200", copies: "1 (Mk II)",  source: "" },
  { element: "Wind", category: "Niche",      name: "Arkab Prior Militis",                   rank: "—",   copies: "1",          source: "" },
  { element: "Wind", category: "Niche",      name: "Tiamat Arc Aura",                       rank: "151", copies: "2",          source: "Omega Rebirth" },
  { element: "Wind", category: "Niche",      name: "Indra's Edge Militis",                  rank: "—",   copies: "1–2",        source: "" },
  { element: "Wind", category: "Niche",      name: "Mandjet",                               rank: "120", copies: "1",          source: "Ennead" },
  { element: "Wind", category: "Niche",      name: "Ancient Nalakuvara",                    rank: "40",  copies: "1",          source: "" },
  { element: "Wind", category: "Niche",      name: "Ewiyar's Beak",                         rank: "151", copies: "1–2",        source: "Ancestral" },
  { element: "Wind", category: "Niche",      name: "Theater of Temperance",                 rank: "151", copies: "—",          source: "" },
  { element: "Wind", category: "Niche",      name: "Melody of Judgement",                   rank: "151", copies: "—",          source: "" },
  { element: "Wind", category: "Niche",      name: "Peridot Crossbow",                      rank: "—",   copies: "—",          source: "" },
  { element: "Wind", category: "Niche",      name: "Exo Australis",                         rank: "—",   copies: "0–1",        source: "" },
  { element: "Wind", category: "Niche",      name: "Abu Simbel",                            rank: "120", copies: "1",          source: "Ennead" },
  { element: "Wind", category: "Niche",      name: "Bahamut Weapons",                       rank: "130", copies: "—",          source: "" },
  { element: "Wind", category: "Niche",      name: "Draconic Rod",                          rank: "151", copies: "—",          source: "" },

  // ── Water (Leviathan) ────────────────────────────────────────────
  { element: "Water", category: "Core",       name: "Leviathan Gaze Mare",                  rank: "151", copies: "3–4",        source: "Omega Rebirth" },
  { element: "Water", category: "Core",       name: "Leviathan Cranium Mare",               rank: "151", copies: "1–2",        source: "Omega Rebirth" },
  { element: "Water", category: "Core",       name: "Exo Antaeus",                          rank: "—",   copies: "0–1",        source: "" },
  { element: "Water", category: "Core",       name: "Staff of Renunciation",                rank: "120", copies: "1",          source: "" },
  { element: "Water", category: "Core",       name: "Doombringer Edge",                     rank: "300", copies: "1",          source: "" },
  { element: "Water", category: "Additional", name: "Uraeus",                               rank: "120", copies: "1",          source: "Ennead" },
  { element: "Water", category: "Additional", name: "Schrodinger",                          rank: "200", copies: "2 (Mk II)",  source: "" },
  { element: "Water", category: "Additional", name: "Lagrange",                             rank: "200", copies: "1–2 (Mk II)",source: "" },
  { element: "Water", category: "Additional", name: "Demonsword of Mortality Verboten",     rank: "151", copies: "2–3",        source: "Odious" },
  { element: "Water", category: "Additional", name: "Cyclestaff of Mortality Verboten",     rank: "151", copies: "2",          source: "Odious" },
  { element: "Water", category: "Additional", name: "Tyros Zither",                         rank: "120", copies: "1–2",        source: "Regalia" },
  { element: "Water", category: "Additional", name: "Judgment of Torrential Tides",         rank: "200", copies: "—",          source: "" },
  { element: "Water", category: "Niche",      name: "Wamdus's Cnidocyte",                   rank: "151", copies: "2",          source: "Ancestral" },
  { element: "Water", category: "Niche",      name: "Winter's Frostnettle",                 rank: "—",   copies: "—",          source: "" },
  { element: "Water", category: "Niche",      name: "Ancient Auberon",                      rank: "40",  copies: "1–2",        source: "" },
  { element: "Water", category: "Niche",      name: "Leviathan Spear Omega",                rank: "101", copies: "1",          source: "" },
  { element: "Water", category: "Niche",      name: "Leviathan Blade Mare",                 rank: "151", copies: "2",          source: "Omega Rebirth" },
  { element: "Water", category: "Niche",      name: "Terrorbow of Mortality Verboten",      rank: "151", copies: "0–1",        source: "Odious" },
  { element: "Water", category: "Niche",      name: "Reflection of The Moon",               rank: "151", copies: "—",          source: "" },
  { element: "Water", category: "Niche",      name: "Wilhelm Militis",                       rank: "—",   copies: "1–2",        source: "" },
  { element: "Water", category: "Niche",      name: "Exo Ephialtes",                        rank: "—",   copies: "0–1",        source: "" },
  { element: "Water", category: "Niche",      name: "Aquamarine Hatchet",                   rank: "—",   copies: "—",          source: "" },
  { element: "Water", category: "Niche",      name: "Glacial Militis",                      rank: "—",   copies: "1",          source: "" },
  { element: "Water", category: "Niche",      name: "Spirit of Mana",                       rank: "120", copies: "1",          source: "Regalia" },
  { element: "Water", category: "Niche",      name: "Draconic Buster",                      rank: "151", copies: "—",          source: "" },
  { element: "Water", category: "Niche",      name: "Bahamut Weapons",                      rank: "130", copies: "—",          source: "" },

  // ── Earth (Yggdrasil) ────────────────────────────────────────────
  { element: "Earth", category: "Core",       name: "Yggdrasil Crystal Blade Arbos",        rank: "151", copies: "3–4",        source: "Omega Rebirth" },
  { element: "Earth", category: "Core",       name: "Ancient Perseus",                      rank: "40",  copies: "1",          source: "" },
  { element: "Earth", category: "Core",       name: "Fang of the Dragonslayer",             rank: "200", copies: "3–4 (Mk II)",source: "" },
  { element: "Earth", category: "Core",       name: "Harp of Renunciation",                 rank: "120", copies: "1",          source: "" },
  { element: "Earth", category: "Core",       name: "Doombringer Trident",                  rank: "300", copies: "1",          source: "" },
  { element: "Earth", category: "Additional", name: "Lusterbow of Desire Verboten",         rank: "151", copies: "2–3",        source: "Odious" },
  { element: "Earth", category: "Additional", name: "Heartstrings of Desire Verboten",      rank: "151", copies: "2",          source: "Odious" },
  { element: "Earth", category: "Additional", name: "Demonedge of Desire Verboten",         rank: "151", copies: "1–2",        source: "Odious" },
  { element: "Earth", category: "Additional", name: "Claw of the Dragonslayer",             rank: "200", copies: "1 (Mk II)",  source: "" },
  { element: "Earth", category: "Additional", name: "Ished",                                rank: "120", copies: "1",          source: "Ennead" },
  { element: "Earth", category: "Additional", name: "Solomon's Axe Militis",                rank: "—",   copies: "1",          source: "" },
  { element: "Earth", category: "Additional", name: "Yggdrasil Bark Bracer Arbos",          rank: "151", copies: "1–2",        source: "Omega Rebirth" },
  { element: "Earth", category: "Additional", name: "Yggdrasil Dewdrop Harp Arbos",         rank: "151", copies: "1–2",        source: "Omega Rebirth" },
  { element: "Earth", category: "Additional", name: "Bounty of Gracious Earth",             rank: "200", copies: "—",          source: "" },
  { element: "Earth", category: "Niche",      name: "Exo Ashavan",                          rank: "—",   copies: "0–1",        source: "" },
  { element: "Earth", category: "Niche",      name: "Tribunal Lyre Militis",                rank: "—",   copies: "1",          source: "" },
  { element: "Earth", category: "Niche",      name: "Nibelung Horn",                        rank: "120", copies: "1–3",        source: "Regalia" },
  { element: "Earth", category: "Niche",      name: "Godsworn Edge",                        rank: "120", copies: "1",          source: "Regalia" },
  { element: "Earth", category: "Niche",      name: "Binds of The Hanged Man",              rank: "151", copies: "—",          source: "" },
  { element: "Earth", category: "Niche",      name: "Galleon's Jaw",                        rank: "151", copies: "1",          source: "Ancestral" },
  { element: "Earth", category: "Niche",      name: "Exo Kshathra",                         rank: "—",   copies: "0–1",        source: "" },
  { element: "Earth", category: "Niche",      name: "Zircon Edge",                          rank: "—",   copies: "—",          source: "" },
  { element: "Earth", category: "Niche",      name: "Tatjenen",                             rank: "120", copies: "1",          source: "Ennead" },
  { element: "Earth", category: "Niche",      name: "Draconic Bow",                         rank: "151", copies: "—",          source: "" },
  { element: "Earth", category: "Niche",      name: "Bahamut Weapons",                      rank: "130", copies: "—",          source: "" },

  // ── Light (Luminiera) ────────────────────────────────────────────
  { element: "Light", category: "Core",       name: "Luminiera Bolt Credo",                 rank: "151", copies: "3–4",        source: "Omega Rebirth" },
  { element: "Light", category: "Core",       name: "Exo Heliocentrum",                     rank: "—",   copies: "0–1",        source: "" },
  { element: "Light", category: "Core",       name: "Sword of Renunciation",                rank: "120", copies: "1",          source: "" },
  { element: "Light", category: "Core",       name: "Doombringer Bow",                      rank: "300", copies: "1",          source: "" },
  { element: "Light", category: "Additional", name: "Blightrifle of Knowledge Verboten",        rank: "151", copies: "3",          source: "Odious" },
  { element: "Light", category: "Additional", name: "Machinahand of Knowledge Verboten",       rank: "151", copies: "2",          source: "Odious" },
  { element: "Light", category: "Additional", name: "Spirelance of Knowledge Verboten",        rank: "151", copies: "1–2",        source: "Odious" },
  { element: "Light", category: "Additional", name: "Concordia",                            rank: "200", copies: "1–2 (Mk II)",source: "" },
  { element: "Light", category: "Additional", name: "Luminiera Saber Credo",                rank: "151", copies: "1–2",        source: "Omega Rebirth" },
  { element: "Light", category: "Additional", name: "Exo Aristarchus",                      rank: "—",   copies: "0–1",        source: "" },
  { element: "Light", category: "Additional", name: "Luminiera Lance Credo",                rank: "151", copies: "1–2",        source: "Omega Rebirth" },
  { element: "Light", category: "Additional", name: "Phantom Fangs",                        rank: "—",   copies: "1–2",        source: "" },
  { element: "Light", category: "Additional", name: "Radiance of Insightful Rebirth",       rank: "200", copies: "—",          source: "" },
  { element: "Light", category: "Niche",      name: "Luminiera Sword Omega",                rank: "101", copies: "2–3",        source: "" },
  { element: "Light", category: "Niche",      name: "Pillar of Flame",                      rank: "120", copies: "2–3",        source: "Regalia" },
  { element: "Light", category: "Niche",      name: "Harakhte",                             rank: "120", copies: "1–2",        source: "Ennead" },
  { element: "Light", category: "Niche",      name: "Heliogabalus Militis",                 rank: "—",   copies: "1",          source: "" },
  { element: "Light", category: "Niche",      name: "Harsiesis",                            rank: "120", copies: "1",          source: "Ennead" },
  { element: "Light", category: "Niche",      name: "Shooting of The Star",                 rank: "151", copies: "—",          source: "" },
  { element: "Light", category: "Niche",      name: "Vital Arc",                            rank: "—",   copies: "—",          source: "" },
  { element: "Light", category: "Niche",      name: "Draconic Blade",                       rank: "151", copies: "—",          source: "" },
  { element: "Light", category: "Niche",      name: "Bahamut Weapons",                      rank: "130", copies: "—",          source: "" },

  // ── Dark (Celeste) ───────────────────────────────────────────────
  { element: "Dark", category: "Core",       name: "Celeste Grace Ater",                    rank: "151", copies: "3–4",        source: "Omega Rebirth" },
  { element: "Dark", category: "Core",       name: "Celeste Saber Ater",                    rank: "151", copies: "2",          source: "Omega Rebirth" },
  { element: "Dark", category: "Core",       name: "Exo Hamartia",                          rank: "—",   copies: "0–1",        source: "" },
  { element: "Dark", category: "Core",       name: "Katana of Renunciation",                rank: "120", copies: "1",          source: "" },
  { element: "Dark", category: "Core",       name: "Doombringer Lyre",                      rank: "300", copies: "1",          source: "" },
  { element: "Dark", category: "Additional", name: "Spiritcleaver of Sanctity Verboten",       rank: "151", copies: "3",          source: "Odious" },
  { element: "Dark", category: "Additional", name: "Ritesword of Sanctity Verboten",           rank: "151", copies: "1–2",        source: "Odious" },
  { element: "Dark", category: "Additional", name: "Codex of Sanctity Verboten",               rank: "151", copies: "1",          source: "Odious" },
  { element: "Dark", category: "Additional", name: "Zechariah",                             rank: "120", copies: "1",          source: "Regalia" },
  { element: "Dark", category: "Additional", name: "Forbidden Agastia",                     rank: "200", copies: "2–4 (Mk II)",source: "" },
  { element: "Dark", category: "Additional", name: "Forsaken Agastia",                      rank: "200", copies: "1–2 (Mk II)",source: "" },
  { element: "Dark", category: "Additional", name: "Celeste Dagger Ater",                   rank: "151", copies: "1–2",        source: "Omega Rebirth" },
  { element: "Dark", category: "Additional", name: "Abyss Spine",                           rank: "120", copies: "2",          source: "Regalia" },
  { element: "Dark", category: "Additional", name: "Festering of Mournful Obsequies",       rank: "200", copies: "—",          source: "" },
  { element: "Dark", category: "Niche",      name: "Pain of Death",                         rank: "151", copies: "—",          source: "" },
  { element: "Dark", category: "Niche",      name: "Ancient Cortana",                       rank: "40",  copies: "1",          source: "" },
  { element: "Dark", category: "Niche",      name: "Fediel's Spine",                        rank: "120", copies: "1–2",        source: "Ancestral" },
  { element: "Dark", category: "Niche",      name: "Ramsund Militis",                       rank: "—",   copies: "1–2",        source: "" },
  { element: "Dark", category: "Niche",      name: "Exo Evilenes",                          rank: "—",   copies: "0–1",        source: "" },
  { element: "Dark", category: "Niche",      name: "Agonize",                               rank: "120", copies: "0–2",        source: "Malice" },
  { element: "Dark", category: "Niche",      name: "Stygian Claw",                          rank: "—",   copies: "—",          source: "" },
  { element: "Dark", category: "Niche",      name: "Abydos",                                rank: "120", copies: "1",          source: "Ennead" },
  { element: "Dark", category: "Niche",      name: "Vynateya Militis",                      rank: "—",   copies: "0–1",        source: "" },
  { element: "Dark", category: "Niche",      name: "Draconic Fire",                         rank: "151", copies: "—",          source: "" },
  { element: "Dark", category: "Niche",      name: "Bahamut Weapons",                       rank: "130", copies: "—",          source: "" },
];
